# Generated by Django 2.2.16 on 2022-04-07 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('composition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.RemoveField(
            model_name='titles',
            name='genre',
        ),
        migrations.CreateModel(
            name='GenreTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='composition.Genres')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='composition.Titles')),
            ],
        ),
        migrations.AddField(
            model_name='titles',
            name='genre',
            field=models.ManyToManyField(through='composition.GenreTitle', to='composition.Genres'),
        ),
    ]
