# Generated by Django 2.2.16 on 2022-04-07 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('composition', '0002_auto_20220407_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titles',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Введите категорию произведения', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titles', to='composition.Categories', verbose_name='Категория'),
        ),
    ]
